### ISSUE TITLE
I find sysmon can not log FileCreate events, bug other type can be logged, do you have met this problem?

### ISSUE THREAD

**Issue by BlackKD** [oz9un/SysmonForLinux-Manual#1]
sysmon -c /opt/sysmon/config.xml

Sysmon v1.0.2 - Monitors system events
Sysinternals - www.sysinternals.com
By Mark Russinovich, Thomas Garnier and Kevin Sheldrake
Copyright (C) 2014-2021 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.

Loading configuration file with schema version 4.70
Sysmon schema version: 4.81
Configuration file validated.

Event SYSMONEVENT_PROCESS_TERMINATE
	RuleName: -
	UtcTime: 2022-09-26 08:05:14.789
	ProcessGuid: {00000000-0000-0000-0000-000000000000}
	ProcessId: 4285
	Image: <unknown process>
	User: root
Event SYSMONEVENT_PROCESS_TERMINATE
	RuleName: -
	UtcTime: 2022-09-26 08:05:14.790
	ProcessGuid: {00000000-0000-0000-0000-000000000000}
	ProcessId: 4286
	Image: <unknown process>
	User: root
Event SYSMONEVENT_CREATE_PROCESS
	RuleName: -
	UtcTime: 2022-09-26 08:05:15.341
	ProcessGuid: {20220824-5d3b-6331-31a8-5e90fb550000}
	ProcessId: 4287
	Image: /usr/bin/sysmon
	FileVersion: -
	Description: -
	Product: -
	Company: -
	OriginalFileName: -
	CommandLine: sysmon -c /opt/sysmon/config.xml
	CurrentDirectory: /root
	User: root
	LogonGuid: {20220824-4111-6331-0000-000004000000}
	LogonId: 0
	TerminalSessionId: 22
	IntegrityLevel: no level
	Hashes: -
	ParentProcessGuid: {00000000-0000-0000-0000-000000000000}
	ParentProcessId: 3184
	ParentImage: -
	ParentCommandLine: -
	ParentUser: -
Event SYSMONEVENT_SERVICE_CONFIGURATION_CHANGE
	UtcTime: 2022-09-26 08:05:15.348
	Configuration: /opt/sysmon/config.xml
	ConfigurationFileHash: -

**Comment by BlackKD** [comment]
I test like "touch /tmp/eee"

whether I use -c config or use -i   ,  it always not log FileCreate events


Linux iZ2ze1phreo2hbt82t63x0Z 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oz9un** [comment]
Hey @BlackKD , I actually wrote a Medium article specifically targeting that 'File Create Events'. You can check it from: https://ozgunkultekin.medium.com/sysmonforlinux-logging-file-create-events-da082dd3f893 

If problem still exists after that, we can discuss that issue again! Thanks for issue.
